name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository  # Caminho de cache para dependências do Maven
        key: ${{ runner.os }}-maven-${{ hashFiles('**/*.java') }}  # Chave única para o cache
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test
